### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by giboow** [giboow/giboow.github.io-old#1]
Error on project build, error on CommentCounter component..

``` r, engine='bash', count_lines
$ npm run build

> giboow-dot-io@ build /Users/philippe/git/giboow.github.io
> phenomic build

  phenomic:builder ✓ Static build: assets copy completed +0ms
  phenomic:builder ✓ Static build: client build completed +15s
  phenomic:builder ✓ Static build: static build completed +2s
  phenomic:static ✗ Static build failed +383ms
/Users/philippe/git/giboow.github.io/node_modules/phenomic/lib/static/index.js:13
      throw error;
      ^

ReferenceError: document is not defined
    at Counter._addDisqusScript (eval at <anonymous> (/Users/philippe/git/giboow.github.io/node_modules/.cache/phenomic/phenomic.node.bundle.js:5:649), <anonymous>:61:20)
    at Counter.componentWillMount (eval at <anonymous> (/Users/philippe/git/giboow.github.io/node_modules/.cache/phenomic/phenomic.node.bundle.js:5:649), <anonymous>:35:12)
    at ReactCompositeComponentMixin.performInitialMount (/Users/philippe/git/giboow.github.io/node_modules/react/lib/ReactCompositeComponent.js:368:12)
    at ReactCompositeComponentMixin.mountComponent (/Users/philippe/git/giboow.github.io/node_modules/react/lib/ReactCompositeComponent.js:262:21)
    at Object.ReactReconciler.mountComponent (/Users/philippe/git/giboow.github.io/node_modules/react/lib/ReactReconciler.js:47:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/philippe/git/giboow.github.io/node_modules/react/lib/ReactMultiChild.js:242:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/philippe/git/giboow.github.io/node_modules/react/lib/ReactDOMComponent.js:677:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/philippe/git/giboow.github.io/node_modules/react/lib/ReactDOMComponent.js:535:29)
    at Object.ReactReconciler.mountComponent (/Users/philippe/git/giboow.github.io/node_modules/react/lib/ReactReconciler.js:47:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/philippe/git/giboow.github.io/node_modules/react/lib/ReactMultiChild.js:242:44)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! giboow-dot-io@ build: `phenomic build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the giboow-dot-io@ build script 'phenomic build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the giboow-dot-io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     phenomic build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs giboow-dot-io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls giboow-dot-io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/philippe/git/giboow.github.io/npm-debug.log
```

**Comment by giboow** [comment]
GIT_DEPLOY_REPO must be set in travis conf file (.travis.yml)

```
....
env:
  global:
    #GH_TOKEN
    - secure: ......
    - GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/giboow/giboow.github.io.git
```
